[tool.ruff]
line-length    = 99
target-version = 'py312'

[tool.ruff.lint]
select = ['ALL']
ignore = ['N802', 'PT028', 'RUF', 'TD', 'FIX']

# Configure single quotes
[tool.ruff.format]
line-ending = 'lf'
quote-style = 'single'
